<?xml version="1.0" encoding="UTF-8"?><testrun name="AppiumTest (1)" project="Appium" tests="1" started="0" failures="0" errors="2" ignored="0">
  <testsuite name="tests.AppiumTest" incomplete="true">
    <error>org.openqa.selenium.WebDriverException: Connection refused: connect
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:05:20.749Z'
System info: host: 'LIS-GXDJQ72', ip: '10.156.124.168', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_211'
Driver info: driver.version: AndroidDriver&#13;
	at io.appium.java_client.remote.AppiumCommandExecutor.lambda$5(AppiumCommandExecutor.java:251)&#13;
	at java.util.Optional.orElseGet(Unknown Source)&#13;
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)&#13;
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)&#13;
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)&#13;
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)&#13;
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)&#13;
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)&#13;
	at org.openqa.selenium.remote.RemoteWebDriver.&lt;init&gt;(RemoteWebDriver.java:130)&#13;
	at io.appium.java_client.DefaultGenericMobileDriver.&lt;init&gt;(DefaultGenericMobileDriver.java:38)&#13;
	at io.appium.java_client.AppiumDriver.&lt;init&gt;(AppiumDriver.java:84)&#13;
	at io.appium.java_client.AppiumDriver.&lt;init&gt;(AppiumDriver.java:94)&#13;
	at io.appium.java_client.android.AndroidDriver.&lt;init&gt;(AndroidDriver.java:95)&#13;
	at tests.AppiumTest.setUp(AppiumTest.java:54)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.net.ConnectException: Connection refused: connect&#13;
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)&#13;
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)&#13;
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)&#13;
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)&#13;
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)&#13;
	at java.net.PlainSocketImpl.connect(Unknown Source)&#13;
	at java.net.SocksSocketImpl.connect(Unknown Source)&#13;
	at java.net.Socket.connect(Unknown Source)&#13;
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)&#13;
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)&#13;
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)&#13;
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)&#13;
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)&#13;
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)&#13;
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)&#13;
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)&#13;
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)&#13;
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)&#13;
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)&#13;
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)&#13;
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)&#13;
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)&#13;
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)&#13;
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)&#13;
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)&#13;
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)&#13;
	at okhttp3.RealCall.execute(RealCall.java:77)&#13;
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)&#13;
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)&#13;
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)&#13;
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)&#13;
	... 27 more&#13;
&#13;
java.lang.NullPointerException&#13;
	at tests.AppiumTest.teardown(AppiumTest.java:79)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    <testcase name="testCal" classname="tests.AppiumTest" incomplete="true"/>
  </testsuite>
</testrun>
